# Generated by Django 3.2.9 on 2021-11-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='ingredients',
            field=models.CharField(max_length=500),
        ),
    ]
