# Generated by Django 3.2.9 on 2021-11-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_information', '0002_alter_foodentry_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='name',
            field=models.CharField(default='name not addded', max_length=200),
            preserve_default=False,
        ),
    ]
